jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: step
        run: python3 --version

name: workflow

'on':
  pull_request:
    branches: [master]
  push:
    branches: [master]
  schedule:
    # generated randomly
    - cron: '22 6 * * MON'
